name: docker

on:
  push:
    # - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: build-and-push
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: authenticate to docker
      run: gcloud auth configure-docker
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/valheim-server:latest
        context: docker
